version: '3.9'
services:
    backend:
      build:
        context:  D:/echo-link/echolink-back
        dockerfile: ./backend/Dockerfile
      ports:
        - "4000:4000"
      volumes:
        - .:/app
      environment:
        - MONGO_URI=mongodb://mongo:27017/echolink
      depends_on:
        - mongo

    mongo:
      image: mongo:6.0
      container_name: mongodb
      ports:
        - "27017:27017"
      volumes:
        - mongo-data:/data/db

volumes:
    mongo-data: